version: '3.8'

services:
  ufw-web-manager:
    build: .
    container_name: ufw-web-manager
    restart: unless-stopped
    ports:
      - "5000"
    environment:
      - FLASK_ENV=production
      - ADMIN_DEFAULT_PASSWORD=ufw-admin-2024
    volumes:
      # Mount host's UFW configuration with write access
      - /etc/ufw:/etc/ufw
      - /lib/ufw:/lib/ufw:ro
      - /usr/share/ufw:/usr/share/ufw:ro
      - /var/lib/ufw:/var/lib/ufw
      # Mount UFW log files
      - /var/log/ufw.log:/var/log/ufw.log:ro
      - /var/log/kern.log:/var/log/kern.log:ro
      - /var/log/syslog:/var/log/syslog:ro
      # Mount host's network configuration for UFW access
      - /sys/class/net:/sys/class/net:ro
    networks:
      - ufw_manager_network
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    devices:
      - /dev/net/tun
    security_opt:
      - apparmor:unconfined
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ufw-web-manager.rule=Host(`firewall.moloko-mokubedi.co.za`)"
      - "traefik.http.routers.ufw-web-manager.entrypoints=websecure"
      - "traefik.http.routers.ufw-web-manager.tls=true"
      - "traefik.http.routers.ufw-web-manager.tls.certresolver=letsencrypt"
      - "traefik.http.services.ufw-web-manager.loadbalancer.server.port=5000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:5000/"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 10s

networks:
  ufw_manager_network:
    driver: bridge